# Generated by Django 5.2.5 on 2025-09-01 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_adverts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='publication_date',
            field=models.DateField(blank=True, null=True, verbose_name='дата публикации'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='characteristics',
            field=models.JSONField(blank=True, null=True, verbose_name='характеристики'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='price',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='year_of_issue',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='год выпуска'),
        ),
    ]
