# Generated by Django 5.2.5 on 2025-09-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_adverts', '0003_rename_city_id_advert_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='название'),
        ),
    ]
