# Generated by Django 5.2.5 on 2025-09-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_adverts', '0004_alter_advert_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='title',
            field=models.CharField(default='Без названия', max_length=255),
        ),
    ]
