# Generated by Django 5.2.5 on 2025-09-02 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_adverts', '0005_alter_city_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='title',
            field=models.CharField(default=True, max_length=255),
        ),
    ]
