# Generated by Django 5.2.5 on 2025-09-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_adverts', '0006_alter_city_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='city',
            name='alias',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='url параметр'),
        ),
        migrations.AlterField(
            model_name='city',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
